### ISSUE TITLE
캐릭터

### ISSUE THREAD

**Issue by overthename** [checkmate2022/Backend#6]
### Product Backlog
캐릭터

### Sprint Backlog

- [x] 캐릭터 생성
- [x] 캐릭터 수정
- [x] 캐릭터 삭제
- [x] 캐릭터 조회
- [x] 캐릭터 기본설정
- [x] 캐릭터 이름중복확인
- [x] 테스트

**Comment by jifrozen0110** [comment]
아바타 controller 제외 테스트 완
controller 오류로 일정 후로 미룸
